version: "2"

services:

  speedy:
    container_name: speedy
    build:
      context: ./docker/speedy/
    ports:
      - "3001:3001"
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=8086
      - DB_NAME=speedy
    volumes:
      - ./docker/speedy/:/home/
    links:
      - db
    command: ["yarn", "run", "start:dev"]



