version: "2"

services:

  db:
    extends:
      file: common.yml
      service: db

  grafana:
    extends:
      file: common.yml
      service: grafana
    depends_on:
      - db

  speedy:
    container_name: speedy
    build:
      context: ./docker/speedy
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=8086
      - DB_NAME=speedy
    volumes:
      - ./docker/speedy/:/home/
    depends_on:
      - db
    command: ["yarn", "run", "start:dev"]



