version: "2"

services:
  db:
    image: tutum/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    env_file:
      - ./docker/influxdb/db.env

  speedy:
    build:
      context: ./docker/speedy/
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=8086
      - DB_NAME=speedy
    links:
      - db
    command: ["yarn", "start:dev"]


